dist: trusty
sudo: required

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install coverage

script:
  - sudo /bin/bash -c "source ~/virtualenv/python3.5/bin/activate && python -m coverage run --source=ndr_netcfg ./setup.py test"

after_success:
  - codecov

