dist: trusty
sudo: required

language: python

python:
  - 3.5

install:
  - pip install codecov
  - pip install coverage
  - pip install netifaces

script:
  - coverage run --source=ndr_netcfg setup.py test

after_success:
  - codecov

